### ISSUE TITLE
setup master64 branch

### ISSUE THREAD

**Issue by paul-ferragut** [elliotwoods/ofxKinectForWindows2#10]
Thanks for the addon I was able to use the master branch and it's great!
however I am not managing to compile the master64 branch
I use visual studio 2013 and this branch of openframeworks: https://github.com/LeoColomb/openFrameworks/tree/Feature-VS2013

The error I got 

Error	5	error C2733: 'GetProcessInformation' : second C linkage of overloaded function not allowed	d:\coding\openframeworks-feature-vs2013\openframeworks-feature-vs2013\libs\quicktime\include\processes.h	195	1	ofxKinectForWindows2Lib

Error	6	error LNK1104: cannot open file 'D:\Coding\openFrameworks-Feature-VS2013\openFrameworks-Feature-VS2013\addons\ofxKinectForWindows2\example\bin\ofxKinectForWindows2Lib.lib'	D:\Coding\openFrameworks-Feature-VS2013\openFrameworks-Feature-VS2013\addons\ofxKinectForWindows2\example\LINK	example

**Comment by elliotwoods** [comment]
closing this for now
feel free to get in touch if you're still having an issue with oF and 64bit
