### ISSUE TITLE
bunch of baseimage.h errors  all on line 26 ,25 ,28,35.... 

### ISSUE THREAD

**Issue by dfamil** [elliotwoods/ofxKinectForWindows2#19]
Error	4	error C3668: 'ofxKinectForWindows2::Source::BaseImage<PixelType,ReaderType,FrameType>::getTexture' : method with override specifier 'override' did not override any base class methods	c:\users\david\google drive\openframeworks\of_v0.8.4_vs_release\addons\ofxkinectforwindows2-ewoods\src\ofxkinectforwindows2\source\BaseImage.h	26	1	myOfxKinectWoods

**Comment by dfamil** [comment]
hi elliot

i used the 0.84version  still got the baseimage.h errors using kinect 1409 bulid 
Error	6	error C3668: 'ofxKinectForWindows2::Source::BaseImage<PixelType,ReaderType,FrameType>::draw' : method with override specifier 'override' did not override any base class methods	c:\users\david\google drive\openframeworks\of_v0.8.4_vs_release\addons\ofxkinectforwindows2\src\ofxkinectforwindows2\source\baseimage.h	36	1	myKInectSketch1a

**Comment by elliotwoods** [comment]
Can you double check that your baseimage.h looks exactly like :
https://github.com/elliotwoods/ofxKinectForWindows2/blob/0.8.4/src/ofxKinectForWindows2/Source/BaseImage.h

If not, please post your file

-- 
Typed by touchscreen

Elliot Woods
elliot@KimchiAndChips.com

UK : +447944977628
KR : +821034458086

**Comment by elliotwoods** [comment]
closing as appears to be an issue with using wrong addon version with wrong oF version
