### ISSUE TITLE
Error pulling Pixel Buffer from Color (fix included)

### ISSUE THREAD

**Issue by rickbarraza** [elliotwoods/ofxKinectForWindows2#21]
Testing out MASTER branch of Addon against OF 0.9.0. 

All video sources work fine in \example\ except COLOR, which returns an error of "Couldn't pull pixel buffer" when attempting to access the color stream.

WHERE THE ERROR OCCURS

Location: Color.CPP

[69]  if (FAILED(frame->CopyConvertedFrameDataToArray(this->pixels.getWidth() * this->pixels.getHeight(), this->pixels.getPixels(), ColorImageFormat_Rgba))) {
}

SOLUTION

Simply changing the first argument for pixel size from a calculated value (this->pixels.getWidth() * this->pixels.getHeight() ) to ( this->pixels.size() ) fixes it.

So the new line should look like this:

[69]  if (FAILED(frame->CopyConvertedFrameDataToArray(this->pixels.size(), this->pixels.getPixels(), ColorImageFormat_Rgba))) {

And it works fine after that.

SETUP

Here is my machine setup. Everything was just pulled down between February 19 and 20.

Windows 8.1
Microsoft Visual Studio Express 2012 for Windows Desktop Update 4
OpenFrameworks, MASTER branch from https://github.com/openframeworks/openFrameworks
ofxKinectForWindows2, MASTER branch from https://github.com/elliotwoods/ofxKinectForWindows2

FYI

@rickbarraza

**Comment by elliotwoods** [comment]
hey rick!
i've pulled your changes

i've been using Kinect Studio for testing (which doesn't have RGB stream).
thanks for testing and spotting this!
