### ISSUE TITLE
Can't find ofxAddonLib.props when using Example with GUI in 0.84 branch

### ISSUE THREAD

**Issue by Taboen** [elliotwoods/ofxKinectForWindows2#33]
When trying to load the exampleWithGui/example.sln file in the 0.84 branch ofxCvGuiLib.vcxproj fails to load.

It tells me it can't find ofxAddonLib.props in libs\ofxAddonLib. When I search on google for this ofxAddonLib it doesn't seem to exist (anymore). 

The other example without GUI works fine.

**Comment by elliotwoods** [comment]
Ah sorry
It's new
Maybe I didn't upload
Will do when back at desk

**Comment by Taboen** [comment]
Thanks!

**Comment by elliotwoods** [comment]
It's uploaded now
https://github.com/elliotwoods/ofxAddonslib
