### ISSUE TITLE
Build error!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by rongloveyan** [elliotwoods/ofxKinectForWindows2#43]
![2 eryjt4t0ou b x nifh](https://cloud.githubusercontent.com/assets/14213560/11414445/3c1aeb30-9430-11e5-99d3-83106078ecea.png)

**Comment by rongloveyan** [comment]
Sorry，I have solve it。

**Comment by elliotwoods** [comment]
:)
looks like you were missing the reference to ofxKinectForWindowsLib in your project
or perhaps had your build environment set for Win32?
