### ISSUE TITLE
Unable to run the bodyIndexShader example in VisualStudio2015

### ISSUE THREAD

**Issue by ConnectedCat** [elliotwoods/ofxKinectForWindows2#50]
Trying to run the code from exampleBodyIndexShader in VS2015, get the following error - see attached. I tried running the same exact code in a brand new project setup - there is no error in this case.
![capture1545_04042016](https://cloud.githubusercontent.com/assets/1493312/14262923/e7021d00-fa85-11e5-8ee0-f7db7da803f5.PNG)

Basic example and bodyIndexColor examples run with no issues.

**Comment by mattfelsen** [comment]
Hey @ConnectedCat, this is a funny Visual Studio issue that has bit me before too:
https://forum.openframeworks.cc/t/unable-to-start-program-ofxoculusdk2/18429/8

Try right-clicking on `example-bodyIndex` in the sidebar (the Solution Explorer) and choose "Set as StartUp project" – you should the bolded project change from `openframeworksLib` (according to your screenshot) to the example project. Hopefully that gets the app starting – no guarantees the example itself is in working order though :stuck_out_tongue_closed_eyes:

**Comment by elliotwoods** [comment]
+1 to what matt said.

Please try and let us know if it still has a problem

**Comment by ConnectedCat** [comment]
Yep, works now. Thank you much!
