### ISSUE TITLE
exampleDepthToCameraTable : load failed

### ISSUE THREAD

**Issue by fdiba** [elliotwoods/ofxKinectForWindows2#62]
Hello,

I tried to load few examples : some are working other don't.

Like exampleDepthToCameraTable. It fails to load. When I try to reload it it says :

F:\of_v0.9.3_vs_release\addons\ofxKinectForWindows2\exampleDepthToCameraTable\exampleDepthToCameraTable.vcxproj : error  : Unable to read the project file "exampleDepthToCameraTable.vcxproj".

Do you know how I can make it work ?

**Comment by elliotwoods** [comment]
That example relies on ofxCvGui
ofxCvGui relies on some other addons also

Let's leave this issue open until ofxCvGui is removed from the example

For the time being perhaps try to recreate the example without ofxCvGui by
looking at important bits of ofApp.cpp directly

**Comment by fdiba** [comment]
Ok thank you for the explanation : I tried to load ofxCvGui but I didn't see it needed also another addon.
