### ISSUE TITLE
Kinect Fusion

### ISSUE THREAD

**Issue by robotpapier** [elliotwoods/ofxKinectForWindows2#75]
Hi, I would like to implement the kinect fusion app to openframeworks.
For now I just use the sample in the kinect 2 SDK and feed a third party app to process the generated mesh.
Do this library implement the fusion part?

Thanks

**Comment by elliotwoods** [comment]
hey @robotpapier 
this addon does not implement kinect fusion sorry.
i'd suggest making this as a separate addon which links to ofxKinectForWindows2
personally I haven't needed this feature in realtime yet so haven't looked into implementing this myself
