### ISSUE TITLE
errors compilation on oF 0.9.8 : glm and ofRotateDeg

### ISSUE THREAD

**Issue by robotpapier** [elliotwoods/ofxKinectForWindows2#77]
Hi,
I have errors when compiling.

name followed by '::' must be a class or namespace name (body.cpp line 21)
Error	C2653	'glm': is not a class or namespace (body.cpp line 21)
Error	C3861	'ofRotateDeg': identifier not found	(Device.cpp	line 369)	

is the addon incompatible with oF 0.9.8 or is it another issue?

Thanks

**Comment by tyhenry** [comment]
You have to use the 0.9.0 branch for any OF version 0.9.8 and lower

(due to some recent updates to ofxKFW2 master branch reflecting changes in
the OF nightly build)

**Comment by robotpapier** [comment]
ok! thanks!

**Comment by tyhenry** [comment]
Sorry 0.9.0 tag not branch

**Comment by robotpapier** [comment]
yep, I found it :)

**Comment by elliotwoods** [comment]
thanks @tyhenry for resolving!
