### ISSUE TITLE
Error in setup addon in visual studio community 2017

### ISSUE THREAD

**Issue by Goodvirus** [elliotwoods/ofxKinectForWindows2#84]
Hello,
     I downloaded openframework version 0.9.8 and also  ofxKinectForWindows2 addon 0.9.0. I also did all steps mentioned in Readme.md file. Still getting following error. Is anybody know how to solve them?

![1](https://user-images.githubusercontent.com/31311332/34414414-42580cce-ec0f-11e7-8128-538b843b598e.png)

Thanks in advance
@elliotwoods @prisonerjohn @memo @kikko @nickdevereaux

**Comment by elliotwoods** [comment]
Heya!
Quick question :
Does the file which it is complaining about exist?

**Comment by Goodvirus** [comment]
Hello Elliotwood,
       Thanks for reply, I didnt find any file ofxKinectForWindowsLib.lib in addon folder. I don't know why this error is occured.

**Comment by elliotwoods** [comment]
https://github.com/elliotwoods/ofxKinectForWindows2/blob/0.9.0/src/ofxKinectForWindows2/Data/Joint.h#L3

This is the file it's complaining about
please can you check if it exists


the lib file is generated by your linker once the addon has been successfully compiled

**Comment by Goodvirus** [comment]
yes the file exists within the project
![2](https://user-images.githubusercontent.com/31311332/34415911-0ffa1792-ec17-11e7-9544-b1e303f26abd.png)

**Comment by elliotwoods** [comment]
Does the file actually exist though?
e.g. if you click on it in the solution explorer, then does it open up
and can you find it in the filesystem?

**Comment by Goodvirus** [comment]
yes file is physically exist at specified directory
![3](https://user-images.githubusercontent.com/31311332/34417354-0e4911ee-ec1e-11e7-9256-213fa1fe63ea.png)
![4](https://user-images.githubusercontent.com/31311332/34417358-12f94b14-ec1e-11e7-805f-edf67ef6275d.png)

**Comment by Goodvirus** [comment]
I added the file directory into including directory of project properties and change command in Utils.h from #include "ofKinectForWindows/Data/Joint.h" to #include <Joint.h> . It solves my problem

Thanks for help @elliotwoods

**Comment by armonnaeini** [comment]
Hi I have the exact same errors as you do, and I have no idea how to solve this. Please someone help me out, I have been struggling with this for too long. When you say you
"added the file directory into including directory of project properties" what do you mean by that??

What is the including directory of project properties? How can I access that?

**Comment by elliotwoods** [comment]
@Goodvirus @armonnaeini - I'm sorry but I'm not familiar with this error fo what could be causing it.

@armonnaeini - Goodvirus is suggesting that you add the folder containing Joint.h directly into your project properties include path by:

1. right click on your Project (e.g. 'emptyExample') in the solution explorer and select 'Properties'
2. On the left navigate to 'C/C++/General'
3. Look for the top entry - 'Additional Include Directories'
4. Click on the text data in the right hand cell, click the down arrow, click Edit. You should get a pop up
5. Add a new entry - the directory which contains Joint.h
6. Edit Utils.h as mentioned by Goodvirus above

**Comment by armonnaeini** [comment]
@elliotwoods 

Thank you so much for your help. That resolved that respective error. I am now getting another error here:

"cannot open file 'C:\Users.......\exampleBodyIndexColor\bin\ofxKinectForWindows2Libd.lib'"

Would you happen to know why I would be receiving this error? Should I take the same steps as before, enter the direct path to the .lib file in the directories panel, within my solution properties?

I guess I would just like to see what is the most viable solution whenever I run into these kinds of petty linking errors. Thanks so much for your help, I seriously appreciate it.

**Comment by elliotwoods** [comment]
if it can't find that lib file, that generally means that it didn't build the addon correctly
try
1) Make sure there is a reference to ofxKinectForWindow2 on your app project, look like:
![image](https://user-images.githubusercontent.com/328294/56016336-d84c3180-5d36-11e9-8146-69fcbe8e1a38.png)

(should also be a reference to openFrameworks too)

2) Try a rebuild solution

**Comment by armonnaeini** [comment]
That's strange, both of those references are present in my solution explorer pane...I don't know what the problem could be here...

**Comment by elliotwoods** [comment]
Ah sorry @Goodvirus - from looking at the screenshots it seems that you're not using the standard folder structure.
That isn't supported by ofxKinectForWindows2Lib (this is mentioned in the readme - maybe could be more explicit)
