### ISSUE TITLE
Unable to compile version of_v0.10.1_vs2017release

### ISSUE THREAD

**Issue by Aurelian24** [elliotwoods/ofxKinectForWindows2#87]
I´ve been using this library for two years now. It works in of_v0.9.8_vs_release version but when i try to compile it in  of_v0.10.1_vs2017_release it doesn´t work. 

This is the error that im getting , what seems to be the problem? where is that file supposed to be? 

What´s going on?

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'libboost_filesystem-vc140-mt-1_64.lib'	ShaderVisualizer	D:\of_v0.10.1_vs2017_release\apps\myApps\ShaderVisualizer\LINK	1

**Comment by Aurelian24** [comment]
UPDATE : 

It seems like the error is when you try to use this library in combination with ofxGuiExtended,

I´ve removed the addon from my solution and the solution compiles !

**Comment by elliotwoods** [comment]
Hey there!
Oh weird, as far as I can find, I'm not using any file functions in ofxKinectForWindows2, so not sure where the conflict with libboost's file functions (which are the draft `std` file functions for >C++14)

I'll close this for now, unless we find out that it's an issue with ofxKFW2 itself

Thank you

**Comment by lutzer** [comment]
i got the same error, when i tried to compile the examples in Visual Studio Community 2017 without upgrading the project to the new Toolset. When opening the Project, simply confirm to upgrade the upgrade and it will compile.

**Comment by elliotwoods** [comment]
thanks @lutzer !
